server:
  port: 8087

rest:
  security:
    realm: x-realm
    issuer-uri: http://localhost:8080/auth/realms/${rest.security.realm}

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/oauth2_demo
        username: user
        password: password

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
              clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
              redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            facebook:
              clientId: 121189305185277
              clientSecret: 42ffe5aa7379e8326387e0fe16f34132
              redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
            github:
              clientId: d3e47fc2ddd966fa4352
              clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
              redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
            keycloak:
              clientId: user-client
              clientSecret: 36d643fb-1520-47c7-82bd-ca1ff5411bbe
              authorizationGrantType: authorization_code
              redirectUri:  "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user
              demo-username: tiger
              demo-password: 123456
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
            keycloak:
              authorizationUri: ${rest.security.issuer-uri}/protocol/openid-connect/auth
              tokenUri: ${rest.security.issuer-uri}/protocol/openid-connect/token
              user-name-attribute: preferred_username
              userInfoUri: ${rest.security.issuer-uri}/protocol/openid-connect/userinfo
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
