server:
  port: 8090

auth:
  realm: x-realm
  issuer-uri: "http://localhost:8080/auth/realms/${auth.realm}"
  client-id: user-client
  client-secret: a29bd208-c0b6-4828-bbfe-9da2e1cdd5fb

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
