server:
  port: 8089

rest:
  security:
    enabled: true
    api-matcher: /api/**
    cors:
      allowed-origins: "*"
      allowed-headers: "*"
      allowed-methods: "GET,POST,PUT,DELETE"
      max-age: 3600

resourceServer:
  resourceId: test-resource-service # will be used to extract the scoped roles for this resource from the jwt id-token

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/x-realm


logging:
  level:
    org:
      springframework:
        security: DEBUG